// openbirds Koka↔Swift bridge (Apple platform).
//
// Two responsibilities:
//
//   1. Provide the C symbols the Koka <host> effect handler dispatches
//      to. POSIX-portable bodies live in `koka/host-ffi.c`; this file
//      adds Apple-specific extras as they appear (Metal blits later,
//      Keychain, APNs).
//
//   2. Expose a plain-C ABI (`bridge.h`) for the Swift shell. Anything
//      Koka-specific (kklib, kk_string_t, kk_context_t, kk_vector_t,
//      kk_ref_t) is hidden; Swift sees only `const char*`,
//      primitives, and raw `uint8_t*` buffers.
//
// Per-platform: this file is the macOS implementation, reused
// verbatim by iOS (both Apple-platform). Android lives elsewhere.

#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <stdio.h>
#include <mach/mach_time.h>

#include <kklib.h>
#include "hello.h"
#include "render.h"
#include "runtime.h"

#include "bridge.h"

// Serialise access to the Koka context. kklib's runtime stores
// thread-local state in `kk_context_t*`, so we must never call into
// Koka from two threads at once. `g_lock` is taken by every public
// bridge function. `openbirds_render_frame` uses `trylock` so a
// concurrent in-progress load doesn't stall the render loop —
// failing to acquire the lock just paints a placeholder this frame
// and the next call retries.
static pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER;

// --- frame-time instrumentation --------------------------------------------
//
// Counts render calls and accumulates wall-clock time per call, prints
// a rolling rate to stderr once per second. Compile-time off-switch:
// `-DOPENBIRDS_NO_FPS_LOG=1` removes the prints (the counters still
// run; their cost is a couple of mach_absolute_time reads per frame).
static uint64_t g_frame_count           = 0;
static uint64_t g_frame_total_ns        = 0;
static uint64_t g_frame_max_ns          = 0;
static uint64_t g_window_start_ns       = 0;
static double   g_mach_ns_per_tick      = 0.0;

static uint64_t bridge_now_ns(void) {
    if (g_mach_ns_per_tick == 0.0) {
        mach_timebase_info_data_t tb;
        mach_timebase_info(&tb);
        g_mach_ns_per_tick = (double)tb.numer / (double)tb.denom;
    }
    return (uint64_t)((double)mach_absolute_time() * g_mach_ns_per_tick);
}

// Aggregate Koka module init/done emitted by Koka's exec-mode build.
// Initialises every transitively imported module (std/core,
// std/num/int64, host, pixel, framebuffer, lzw, gif, runtime,
// render, scene, hello).
extern void kk_hello__main__init(kk_context_t* _ctx);
extern void kk_hello__main__done(kk_context_t* _ctx);

// Generated by Koka from `scene.kk`, `runtime.kk`, and `ttf.kk`.
// Each ref is process-lifetime; the bridge dups for each call so
// Koka can consume the argument per its calling conventions.
extern kk_ref_t kk_scene_new_scene_cell(kk_context_t* _ctx);
extern kk_unit_t kk_scene_handle_tap(kk_ref_t s,
    kk_integer_t x, kk_integer_t y, kk_integer_t w, kk_integer_t h,
    double exit_at_s, kk_context_t* _ctx);
extern bool kk_scene_should_exit(kk_ref_t s, double now, kk_context_t* _ctx);
extern double kk_runtime_gif_duration_s(kk_ref_t s, kk_context_t* _ctx);
extern kk_ref_t kk_truetype_registry_new_font_registry(kk_context_t* _ctx);
extern kk_unit_t kk_truetype_registry_register(kk_ref_t r, kk_string_t name,
    kk_vector_t bytes, kk_context_t* _ctx);
extern kk_ref_t kk_truetype_glyph__cache_new_glyph_cache(kk_context_t* _ctx);
extern kk_ref_t kk_scroll_new_scroll_cell(kk_context_t* _ctx);
extern kk_unit_t kk_scroll_pan_start(kk_ref_t c, double y, double t, kk_context_t* _ctx);
extern kk_unit_t kk_scroll_pan_move(kk_ref_t c, double y, double t, kk_context_t* _ctx);
extern kk_unit_t kk_scroll_pan_end(kk_ref_t c, double t, kk_context_t* _ctx);
extern kk_ref_t kk_render_new_page_cache(kk_context_t* _ctx);

// --- session lifecycle ------------------------------------------------------

static kk_context_t* g_ctx              = NULL;
static kk_ref_t      g_session;
static bool          g_session_init     = false;
static kk_ref_t      g_scene;
static bool          g_scene_init       = false;
static kk_ref_t      g_fonts;
static bool          g_fonts_init       = false;
static kk_ref_t      g_glyphs;
static bool          g_glyphs_init      = false;
static kk_ref_t      g_scroll;
static bool          g_scroll_init      = false;
static kk_ref_t      g_pcache;
static bool          g_pcache_init      = false;

static kk_context_t* ensure_ctx(void) {
    if (g_ctx == NULL) {
        g_ctx = kk_main_start(0, NULL);
        kk_hello__main__init(g_ctx);
    }
    return g_ctx;
}

static kk_ref_t borrow_scene(kk_context_t* ctx) {
    if (!g_scene_init) {
        g_scene      = kk_scene_new_scene_cell(ctx);
        g_scene_init = true;
    }
    return kk_ref_dup(g_scene, ctx);
}

static kk_ref_t borrow_fonts(kk_context_t* ctx) {
    if (!g_fonts_init) {
        g_fonts      = kk_truetype_registry_new_font_registry(ctx);
        g_fonts_init = true;
    }
    return kk_ref_dup(g_fonts, ctx);
}

static kk_ref_t borrow_glyphs(kk_context_t* ctx) {
    if (!g_glyphs_init) {
        g_glyphs      = kk_truetype_glyph__cache_new_glyph_cache(ctx);
        g_glyphs_init = true;
    }
    return kk_ref_dup(g_glyphs, ctx);
}

static kk_ref_t borrow_scroll(kk_context_t* ctx) {
    if (!g_scroll_init) {
        g_scroll      = kk_scroll_new_scroll_cell(ctx);
        g_scroll_init = true;
    }
    return kk_ref_dup(g_scroll, ctx);
}

static kk_ref_t borrow_pcache(kk_context_t* ctx) {
    if (!g_pcache_init) {
        g_pcache      = kk_render_new_page_cache(ctx);
        g_pcache_init = true;
    }
    return kk_ref_dup(g_pcache, ctx);
}

// Lazily create the Koka-side session ref the first time something
// needs it (load-gif or render). The bridge holds ONE reference for
// the process lifetime; per-call we `kk_ref_dup` so each Koka call
// can consume its argument.
static kk_ref_t borrow_session(kk_context_t* ctx) {
    if (!g_session_init) {
        g_session      = kk_runtime_new_session(ctx);
        g_session_init = true;
    }
    return kk_ref_dup(g_session, ctx);
}

void openbirds_shutdown(void) {
    pthread_mutex_lock(&g_lock);
    if (g_ctx != NULL) {
        if (g_session_init) {
            kk_ref_drop(g_session, g_ctx);
            g_session_init = false;
        }
        if (g_scene_init) {
            kk_ref_drop(g_scene, g_ctx);
            g_scene_init = false;
        }
        if (g_fonts_init) {
            kk_ref_drop(g_fonts, g_ctx);
            g_fonts_init = false;
        }
        if (g_glyphs_init) {
            kk_ref_drop(g_glyphs, g_ctx);
            g_glyphs_init = false;
        }
        if (g_scroll_init) {
            kk_ref_drop(g_scroll, g_ctx);
            g_scroll_init = false;
        }
        if (g_pcache_init) {
            kk_ref_drop(g_pcache, g_ctx);
            g_pcache_init = false;
        }
        kk_hello__main__done(g_ctx);
        kk_main_end(g_ctx);
        g_ctx = NULL;
    }
    pthread_mutex_unlock(&g_lock);
}

// --- string greeter (Stage 1) ----------------------------------------------

const char* openbirds_greeting(void) {
    pthread_mutex_lock(&g_lock);
    kk_context_t* ctx = ensure_ctx();
    kk_string_t s = kk_hello_greeting(ctx);
    kk_ssize_t len = 0;
    const char* cbuf = kk_string_cbuf_borrow(s, &len, ctx);
    char* out = (char*)malloc((size_t)len + 1);
    memcpy(out, cbuf, (size_t)len);
    out[len] = '\0';
    kk_string_drop(s, ctx);
    pthread_mutex_unlock(&g_lock);
    return out;
}

void openbirds_free(const char* s) {
    free((void*)s);
}

// --- GIF loading (Stage 3c/Lucile) -----------------------------------------
//
// Wraps a uint8_t* buffer into a Koka `vector<int>` and hands it to
// `runtime/load-gif`. Each byte gets boxed as a kk_integer (small
// integers are immediates on Apple Silicon — no heap alloc).

static kk_vector_t bytes_to_vector_int(const uint8_t* data, int32_t len, kk_context_t* ctx) {
    kk_box_t* buf = NULL;
    kk_vector_t v = kk_vector_alloc_uninit((kk_ssize_t)len, &buf, ctx);
    for (int32_t i = 0; i < len; i++) {
        buf[i] = kk_integer_box(kk_integer_from_int32((int32_t)data[i], ctx), ctx);
    }
    return v;
}

void openbirds_load_gif(const uint8_t* bytes, int32_t len) {
    if (bytes == NULL || len <= 0) return;
    pthread_mutex_lock(&g_lock);
    kk_context_t* ctx = ensure_ctx();
    kk_ref_t      s   = borrow_session(ctx);
    kk_vector_t   v   = bytes_to_vector_int(bytes, len, ctx);
    kk_runtime_load_gif(s, v, ctx);
    // load_gif consumes both s and v per Koka calling conventions.
    pthread_mutex_unlock(&g_lock);
}

// --- font loading (Stage 4b/typography) ------------------------------------
//
// Hand the TTF bytes to the Koka-side parser at `koka/ttf.kk`.
// The brain owns the parser, the rasterizer, the glyph cache,
// and the registry. The bridge does ONLY what bridges should do:
// copy bytes across the language boundary into a Koka
// `vector<int>` and call into Koka. No C TTF library; the
// algorithm is in Koka, same way LZW + GIF parsing are.
void openbirds_load_font(const char* name, const uint8_t* bytes, int32_t len) {
    if (name == NULL || bytes == NULL || len <= 0) return;
    pthread_mutex_lock(&g_lock);
    kk_context_t* ctx = ensure_ctx();
    kk_ref_t      r   = borrow_fonts(ctx);
    kk_string_t   kn  = kk_string_alloc_from_utf8(name, ctx);
    kk_vector_t   kv  = bytes_to_vector_int(bytes, len, ctx);
    kk_truetype_registry_register(r, kn, kv, ctx);
    pthread_mutex_unlock(&g_lock);
    fprintf(stderr, "[openbirds] load_font: name=%s len=%d → koka\n", name, len);
    fflush(stderr);
}

// --- pixel framebuffer ------------------------------------------------------
//
// Calls into Koka's `render::frame-rgba`, which returns a Koka
// `vector<int>` of length width*height — one packed 0xRRGGBBAA
// int per pixel. We unbox each cell (a smallint, immediate on
// 64-bit) and split into the four output bytes. 65k unboxes per
// frame at 256², not 256k — and the per-call work on the Koka side
// is also cut by 4× (no per-byte closure invocation).
//
// The Koka side memoises the rendered buffer per (frame-ix, w, h),
// so on every TimelineView tick where the active frame and size
// haven't changed, the only work here is the unbox + splat loop.
void openbirds_render_frame(double now_seconds,
                            int32_t width_px, int32_t height_px,
                            uint8_t* out_buffer) {
    if (out_buffer == NULL || width_px <= 0 || height_px <= 0) return;

    const uint64_t t0 = bridge_now_ns();

    // trylock: if a load is in flight on a background thread, paint a
    // visible placeholder for this frame instead of blocking the
    // display refresh. The next render retries.
    if (pthread_mutex_trylock(&g_lock) != 0) {
        // Loading-state placeholder: opaque dark grey RGBA.
        const size_t expected = (size_t)width_px * (size_t)height_px * 4u;
        for (size_t i = 0; i < expected; i += 4) {
            out_buffer[i + 0] = 24;
            out_buffer[i + 1] = 24;
            out_buffer[i + 2] = 32;
            out_buffer[i + 3] = 255;
        }
        return;
    }

    kk_context_t* ctx = ensure_ctx();
    kk_ref_t      s   = borrow_session(ctx);
    kk_ref_t      sc  = borrow_scene(ctx);
    kk_ref_t      fr  = borrow_fonts(ctx);
    kk_ref_t      gc  = borrow_glyphs(ctx);
    kk_ref_t      sr  = borrow_scroll(ctx);
    kk_ref_t      pc  = borrow_pcache(ctx);

    kk_integer_t w = kk_integer_from_int32(width_px, ctx);
    kk_integer_t h = kk_integer_from_int32(height_px, ctx);
    kk_vector_t  v = kk_render_frame_rgba(s, sc, fr, gc, sr, pc, now_seconds, w, h, ctx);

    kk_ssize_t len = 0;
    const kk_box_t* boxes = kk_vector_buf_borrow(v, &len, ctx);

    const size_t pixels   = (size_t)width_px * (size_t)height_px;
    const size_t n        = (len > 0 && (size_t)len <= pixels) ? (size_t)len : pixels;

    for (size_t p = 0; p < n; ++p) {
        // Smallint unbox + 64-bit clamp — both inline-fast on Apple
        // Silicon (no heap, no allocation; the unbox is a tag strip
        // and the clamp is a cast for in-range smallints). We need
        // int64 (not int32) because a fully-opaque pixel packs as
        // 0xRRGGBBAA which is > INT32_MAX; clamp32 would saturate.
        kk_integer_t  ki     = kk_integer_unbox(boxes[p], ctx);
        const int64_t packed = kk_integer_clamp64_borrow(ki, ctx);
        const uint32_t up    = (uint32_t)packed;
        const size_t  o      = p * 4u;
        out_buffer[o + 0] = (uint8_t)((up >> 24) & 0xFF);
        out_buffer[o + 1] = (uint8_t)((up >> 16) & 0xFF);
        out_buffer[o + 2] = (uint8_t)((up >>  8) & 0xFF);
        out_buffer[o + 3] = (uint8_t)( up        & 0xFF);
    }

    kk_vector_drop(v, ctx);
    pthread_mutex_unlock(&g_lock);

    const uint64_t t1 = bridge_now_ns();
    const uint64_t dt = t1 - t0;
    g_frame_count++;
    g_frame_total_ns += dt;
    if (dt > g_frame_max_ns) g_frame_max_ns = dt;
    if (g_window_start_ns == 0) g_window_start_ns = t0;
    if (t1 - g_window_start_ns >= 1000000000ull) {
#ifndef OPENBIRDS_NO_FPS_LOG
        const double secs    = (double)(t1 - g_window_start_ns) / 1e9;
        const double fps     = (double)g_frame_count / secs;
        const double avg_ms  = (double)g_frame_total_ns / (double)g_frame_count / 1e6;
        const double max_ms  = (double)g_frame_max_ns / 1e6;
        fprintf(stderr,
                "[openbirds] render: %5.1f fps  avg %5.2f ms  max %6.2f ms  (%llu calls in %.2fs)\n",
                fps, avg_ms, max_ms,
                (unsigned long long)g_frame_count, secs);
        fflush(stderr);
#endif
        g_frame_count     = 0;
        g_frame_total_ns  = 0;
        g_frame_max_ns    = 0;
        g_window_start_ns = t1;
    }
}

// --- input + lifecycle (Stage 4a/close-button) ------------------------------

void openbirds_tap(int32_t x, int32_t y,
                   int32_t width_px, int32_t height_px,
                   double now_seconds) {
    if (width_px <= 0 || height_px <= 0) return;
    pthread_mutex_lock(&g_lock);
    kk_context_t* ctx = ensure_ctx();
    kk_ref_t      sc  = borrow_scene(ctx);
    kk_ref_t      sg  = borrow_session(ctx);
    // Compute the goodbye-animation deadline as `now + gif-duration`
    // so scene.kk doesn't need to know about runtime.kk. If no GIF
    // is loaded yet (e.g. tap landed during the load race) we fall
    // back to a 3-second timeout so the user still gets out.
    double dur = kk_runtime_gif_duration_s(sg, ctx);
    if (dur <= 0.0) dur = 3.0;
    const double exit_at_s = now_seconds + dur;
    kk_integer_t kx = kk_integer_from_int32(x, ctx);
    kk_integer_t ky = kk_integer_from_int32(y, ctx);
    kk_integer_t kw = kk_integer_from_int32(width_px, ctx);
    kk_integer_t kh = kk_integer_from_int32(height_px, ctx);
    kk_scene_handle_tap(sc, kx, ky, kw, kh, exit_at_s, ctx);
    pthread_mutex_unlock(&g_lock);
}

int32_t openbirds_should_exit(double now_seconds) {
    pthread_mutex_lock(&g_lock);
    kk_context_t* ctx = ensure_ctx();
    kk_ref_t      sc  = borrow_scene(ctx);
    bool          ex  = kk_scene_should_exit(sc, now_seconds, ctx);
    pthread_mutex_unlock(&g_lock);
    return ex ? 1 : 0;
}

// --- pan / scroll handlers (Stage 5/scroll) --------------------------------

void openbirds_pan_start(double y, double t) {
    pthread_mutex_lock(&g_lock);
    kk_context_t* ctx = ensure_ctx();
    kk_ref_t      sr  = borrow_scroll(ctx);
    kk_scroll_pan_start(sr, y, t, ctx);
    pthread_mutex_unlock(&g_lock);
}

void openbirds_pan_move(double y, double t) {
    pthread_mutex_lock(&g_lock);
    kk_context_t* ctx = ensure_ctx();
    kk_ref_t      sr  = borrow_scroll(ctx);
    kk_scroll_pan_move(sr, y, t, ctx);
    pthread_mutex_unlock(&g_lock);
}

void openbirds_pan_end(double t) {
    pthread_mutex_lock(&g_lock);
    kk_context_t* ctx = ensure_ctx();
    kk_ref_t      sr  = borrow_scroll(ctx);
    kk_scroll_pan_end(sr, t, ctx);
    pthread_mutex_unlock(&g_lock);
}
